import json
import os
from google import genai


def _gemini_client():
    if os.environ.get("GEMINI_API_KEY"):
        return genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    return genai.Client(vertexai=True, project=os.environ["GOOGLE_CLOUD_PROJECT"], location="us-central1")


def _default_gemini(prompt: str) -> tuple[str, str]:
    client = _gemini_client()
    response = client.models.generate_content(model="gemini-2.5-flash", contents=prompt)
    text = response.text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
    try:
        parsed = json.loads(text)
        return parsed.get("patch", ""), parsed.get("fix_explanation", "")
    except Exception:
        return text, "Fix generated by Gemini."


def generate_fix(
    hit: dict,
    traces: list[dict],
    precedents: list[dict],
    _gemini_fn=None,
) -> dict:
    if _gemini_fn is None:
        _gemini_fn = _default_gemini

    ctx = hit.get("incident_context", {})
    lines = hit.get("matching_lines", [])
    history = hit.get("per_service_history", [])

    prompt = f"""You are a senior engineer generating a targeted code fix.

DANGEROUS PATTERN FOUND:
File: {hit['file_path']}
Matching lines: {json.dumps(lines, indent=2)}

INCIDENT CONTEXT:
{json.dumps(ctx, indent=2)}

DYNATRACE TRACES:
{json.dumps(traces[:3], indent=2) if traces else "No trace data available."}

PREVIOUS FIX PRECEDENTS:
{json.dumps(precedents[:3], indent=2) if precedents else "No precedents found."}

PER-SERVICE HISTORY:
{json.dumps(history, indent=2) if history else "No history."}

Generate a minimal fix. Return JSON with exactly two fields:
- patch: unified diff string fixing the dangerous line (add timeout=5 to the HTTP call)
- fix_explanation: one sentence citing the incident ID and what the fix prevents

Respond with only the JSON object, no markdown."""

    patch, explanation = _gemini_fn(prompt)

    return {"patch": patch, "fix_explanation": explanation}
