import json
import os
from google import genai


def _gemini_client():
    if os.environ.get("GEMINI_API_KEY"):
        return genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    return genai.Client(vertexai=True, project=os.environ["GOOGLE_CLOUD_PROJECT"], location="us-central1")


def _default_gemini(prompt: str) -> tuple[str, str]:
    client = _gemini_client()
    response = client.models.generate_content(model="gemini-2.5-flash", contents=prompt)
    text = response.text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
    try:
        parsed = json.loads(text)
        return parsed.get("patch", ""), parsed.get("fix_explanation", "")
    except Exception:
        return text, "Fix generated by Gemini."


def generate_fix(
    hit: dict,
    traces: list[dict],
    precedents: list[dict],
    _gemini_fn=None,
) -> dict:
    if _gemini_fn is None:
        _gemini_fn = _default_gemini

    ctx = hit.get("incident_context", {})
    lines = hit.get("matching_lines", [])
    history = hit.get("per_service_history", [])

    prompt = f"""You are a senior engineer generating a targeted code fix.

DANGEROUS PATTERN FOUND:
File: {hit['file_path']}
Matching lines: {json.dumps(lines, indent=2)}

INCIDENT CONTEXT:
{json.dumps(ctx, indent=2)}

DYNATRACE TRACES:
{json.dumps(traces[:3], indent=2) if traces else "No trace data available."}

PREVIOUS FIX PRECEDENTS:
{json.dumps(precedents[:3], indent=2) if precedents else "No precedents found."}

PER-SERVICE HISTORY:
{json.dumps(history, indent=2) if history else "No history."}

Generate a minimal fix. Return JSON with exactly two fields:
- patch: unified diff string fixing the dangerous line (add timeout=5 to the HTTP call)
- fix_explanation: one sentence citing the incident ID and what the fix prevents

Respond with only the JSON object, no markdown."""

    patch, explanation = _gemini_fn(prompt)

    return {"patch": patch, "fix_explanation": explanation}


def run_with_correction(
    hit: dict,
    traces: list,
    precedents: list,
    max_iterations: int = 3,
    _fix_fn=None,
    _eval_fn=None,
    _mr_fn=None,
    _store_fn=None,
) -> dict:
    from fix_factory.evaluator import evaluate_fix
    from fix_factory.tools.gitlab_mr import create_mr
    from fix_factory.tools.mongodb_outcomes import store_outcome

    if _fix_fn is None:
        _fix_fn = generate_fix
    if _eval_fn is None:
        _eval_fn = evaluate_fix
    if _mr_fn is None:
        _mr_fn = create_mr
    if _store_fn is None:
        _store_fn = store_outcome

    last_rationale = ""
    extra_context = ""

    for i in range(max_iterations):
        fix = _fix_fn(hit, traces, precedents)
        if extra_context:
            fix["fix_explanation"] += f" (retry {i+1}: {extra_context})"

        evaluation = _eval_fn(hit, fix["patch"])

        if evaluation["passed"]:
            import os
            gl_token = os.environ.get("GITLAB_TOKEN", "")
            mr_url = _mr_fn(hit["service"], gl_token, hit["file_path"], fix["patch"], hit["incident_context"])
            outcome = {
                "service": hit["service"],
                "file_path": hit["file_path"],
                "mr_url": mr_url,
                "self_correction_passed": True,
                "correction_iterations": i + 1,
                "failure_reason": None,
            }
            _store_fn(outcome)
            return {**fix, **outcome}

        last_rationale = evaluation["rationale"]
        extra_context = last_rationale

    outcome = {
        "service": hit["service"],
        "file_path": hit["file_path"],
        "mr_url": None,
        "self_correction_passed": False,
        "correction_iterations": max_iterations,
        "failure_reason": last_rationale,
    }
    _store_fn(outcome)
    return {**fix, **outcome}
