import json
import os
from google import genai


def _gemini_client():
    if os.environ.get("GEMINI_API_KEY"):
        return genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    return genai.Client(vertexai=True, project=os.environ["GOOGLE_CLOUD_PROJECT"], location="us-central1")


def _default_gemini(prompt: str) -> tuple[str, str, str]:
    client = _gemini_client()
    response = client.models.generate_content(model="gemini-2.5-flash", contents=prompt)
    text = response.text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
    try:
        parsed = json.loads(text)
        return parsed.get("old_line", ""), parsed.get("new_line", ""), parsed.get("fix_explanation", "")
    except Exception:
        return "", "", "Fix generated by Gemini."


def generate_fix(
    hit: dict,
    traces: list[dict],
    precedents: list[dict],
    _gemini_fn=None,
) -> dict:
    if _gemini_fn is None:
        _gemini_fn = _default_gemini

    ctx = hit.get("incident_context", {})
    lines = hit.get("matching_lines", [])
    history = hit.get("per_service_history", [])

    prompt = f"""You are a senior engineer generating a targeted code fix.

DANGEROUS PATTERN FOUND:
File: {hit['file_path']}
Matching lines: {json.dumps(lines, indent=2)}

INCIDENT CONTEXT:
{json.dumps(ctx, indent=2)}

DYNATRACE TRACES:
{json.dumps(traces[:3], indent=2) if traces else "No trace data available."}

PREVIOUS FIX PRECEDENTS:
{json.dumps(precedents[:3], indent=2) if precedents else "No precedents found."}

PER-SERVICE HISTORY:
{json.dumps(history, indent=2) if history else "No history."}

Generate a minimal fix. Return JSON with exactly three fields:
- old_line: the exact line of code to replace, including leading whitespace, exactly as it appears in the file
- new_line: the replacement line, including leading whitespace (add timeout=5 to the HTTP call)
- fix_explanation: one sentence citing the incident ID and what the fix prevents

Respond with only the JSON object, no markdown."""

    old_line, new_line, explanation = _gemini_fn(prompt)
    patch = f"-{old_line}\n+{new_line}" if old_line and new_line else ""

    return {"old_line": old_line, "new_line": new_line, "patch": patch, "fix_explanation": explanation}


def run_with_correction(
    hit: dict,
    traces: list,
    precedents: list,
    max_iterations: int = 3,
    _fix_fn=None,
    _eval_fn=None,
    _mr_fn=None,
    _store_fn=None,
) -> dict:
    from fix_factory.evaluator import evaluate_fix
    from fix_factory.tools.gitlab_mr import create_mr
    from fix_factory.tools.mongodb_outcomes import store_outcome

    if _fix_fn is None:
        _fix_fn = generate_fix
    if _eval_fn is None:
        _eval_fn = evaluate_fix
    if _mr_fn is None:
        _mr_fn = create_mr
    if _store_fn is None:
        _store_fn = store_outcome

    last_rationale = ""
    extra_context = ""
    fix: dict = {"old_line": "", "new_line": "", "patch": "", "fix_explanation": ""}

    for i in range(max_iterations):
        try:
            fix = _fix_fn(hit, traces, precedents)
            if extra_context:
                fix["fix_explanation"] += f" (retry {i+1}: {extra_context})"

            evaluation = _eval_fn(hit, fix["patch"])

            if evaluation["passed"]:
                import os
                gl_token = os.environ.get("GITLAB_TOKEN", "")
                namespace = hit.get("gitlab_namespace", hit["service"])
                evaluated_on = evaluation.get("evaluated_on", "incident_context")
                mr_url = _mr_fn(namespace, gl_token, hit["file_path"], fix["old_line"], fix["new_line"], hit["incident_context"], evaluated_on)
                outcome = {
                    "service": hit["service"],
                    "file_path": hit["file_path"],
                    "mr_url": mr_url,
                    "self_correction_passed": True,
                    "correction_iterations": i + 1,
                    "failure_reason": None,
                    "evaluated_on": evaluated_on,
                }
                _store_fn(outcome)
                return {**fix, **outcome}

            last_rationale = evaluation["rationale"]
            extra_context = last_rationale
        except Exception as e:
            last_rationale = f"Error on iteration {i + 1}: {e}"
            extra_context = last_rationale

    outcome = {
        "service": hit["service"],
        "file_path": hit["file_path"],
        "mr_url": None,
        "self_correction_passed": False,
        "correction_iterations": max_iterations,
        "failure_reason": last_rationale,
    }
    _store_fn(outcome)
    return {**fix, **outcome}
